[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=78", "wheel", "setuptools_scm>=7.1.0", "versionista>=1.1.0"]

[project]
authors = [
  {name = "NCI GDC", email = "gdc_dev_questions-aaaaae2lhsbell56tlvh3upgoq@cdis.slack.com"}
]
classifiers = [
  "Topic :: Internet :: WWW/HTTP :: Indexing/Search",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.13"
]
dependencies = [
  "addict",
  "datadog",
  "deepdiff", # required by compare_indices
  "dictdiffer",
  "elasticsearch",
  "more-itertools",
  "networkx",
  "python-dotenv",
  "python-json-logger",
  "requests",
  "SQLAlchemy",
  "psqlgraph @ git+https://github.com/NCI-GDC/psqlgraph.git@develop",
  "gdcdictionary @ git+https://github.com/theMMRF/mmrf_dictionary.git@master",
  "gdcdatamodel2 @ git+https://github.com/theMMRF/mmrfdatamodel2.git@mmrf",
  "gdc-ng-models @ git+https://github.com/NCI-GDC/gdc-ng-models.git@develop",
  "indexclient @ git+https://github.com/NCI-GDC/indexclient.git@develop",
  "queueclient @ git+https://github.com/NCI-GDC/queueclient.git#develop",
  "gdcmodels @ git+https://github.com/theMMRF/mmrf-models.git#mmrf"
]
description = "Repository for building the GDC Elasticsearch indices."
dynamic = ["version"]
license-files = ["LICENSE"]
name = "esbuild"
readme = "README.md"
requires-python = "~=3.13.0"

[project.optional-dependencies]
dev = [
  "jmespath",
  "mock",
  "pytest",
  "pytest-cov",
  "gdcdatamodel2[visualization]",
  "testcontainers"
]

[project.scripts]
"compare_indices.py" = "esbuild.bin.compare_indices:main"
esbuild-cli = "esbuild.bin.esbuild_cli:main"
"master.py" = "esbuild.bin.master:main"
"minion.py" = "esbuild.bin.minion:main"

[project.urls]
Repository = "https://github.com/NCI-GDC/esbuild"

[tool.coverage.html]
directory = "docs/htmlcov"
title = "esbuild coverage report"

[tool.pytest.ini_options]
testpaths = ["tests/unit", "tests/integration"]

[tool.ruff]
line-length = 95
src = ["src", "tests"]
target-version = "py313"

[tool.ruff.lint]
# see https://docs.astral.sh/ruff/rules/
select = [
  "E", # pydocstyle errors
  "F", # pyflakes
  "I", # isort
  "N", # pep8 naming
  "RUF", # ruff specific rules
  "UP", # pyupgrade
  "D", # pydocstyle lint
  "W" # pydocstyle warnings
]
ignore = [
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D106",
  "D107",
  "D205",
  "D415",
  "E501"
]

[tool.ruff.lint.isort]
known-first-party = ["esbuild", "tests"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
local_scheme = "versionista-local-format"
version_scheme = "versionista-format"
